#%RAML 1.0
title: Wallet API
version: v1
mediaType: application/json
baseUri: hb://wallet

types:
  Wallet:
    type: object
    properties:
      wallet_id: string
      amount:
        type: number
        format: long
        description: represent's currency in cent's (as integers)
      minimum?:
        type: number
        format: long
        description: if minimum is set, amount can't be set to less than minimum (lower bound, often 0)
      maximum?:
        type: number
        format: long
        description: if maximum is set, amount can't be set to less than minimum (upper bound)
      last_transaction_id: string
      updated_at:
        type: number
        format: long

  WalletTransactionStatus:
    enum: [new,applied,failed]

  WalletTransaction:
    type: object
    properties:
      transaction_id: string
      wallet_id: string
      amount:
        type: number
        format: long
      created_at:
        type: number
        format: long
      minimum?:
        type: number
        format: long
      maximum?:
        type: number
        format: long
      status: WalletTransactionStatus
      extra: object

/wallets/{wallet_id}:
  uriParameters:
    wallet_id: string
  get:
    responses:
      200:
        body:
          Wallet

/wallets/{wallet_id}/transactions/{transaction_id}:
  uriParameters:
    wallet_id: string
    transaction_id: string
  put:
    body:
      type: WalletTransaction
    responses:
      201:
        body:
          type: Wallet
      200:
        body:
          type: Wallet

  get:
    responses:
      200:
        body:
          type: WalletTransaction